name: Odoo CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo -d odoo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      PYTHON_VERSION: "3.11"
      DB_HOST: 127.0.0.1
      DB_PORT: "5432"
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: odoo

      ODOO_IMAGE_TAG: local-ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install lint tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest psycopg2-binary

      - name: Ruff (lint)
        run: |
          ruff check .

      - name: Run Unit Tests (pytest)
        run: |
          pytest -q || (echo "No unit tests found / failing - adjust for your repo" && exit 1)

      - name: Integration Test - Postgres connectivity
        run: |
          python - << 'PY'
          import os, time
          import psycopg2

          host=os.environ["DB_HOST"]
          port=os.environ["DB_PORT"]
          user=os.environ["DB_USER"]
          pwd=os.environ["DB_PASSWORD"]
          db=os.environ["DB_NAME"]

          for i in range(30):
              try:
                  conn = psycopg2.connect(host=host, port=port, user=user, password=pwd, dbname=db)
                  cur = conn.cursor()
                  cur.execute("SELECT 1;")
                  print("✅ Postgres OK:", cur.fetchone())
                  conn.close()
                  break
              except Exception as e:
                  print("Waiting Postgres...", e)
                  time.sleep(2)
          else:
              raise SystemExit("❌ Postgres not ready")
          PY

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: my-odoo:${{ env.ODOO_IMAGE_TAG }}

      - name: Run Odoo container for E2E check
        run: |
          docker run -d --name odoo-ci \
            -p 8069:8069 \
            -e HOST=${DB_HOST} \
            -e PORT=${DB_PORT} \
            -e USER=${DB_USER} \
            -e PASSWORD=${DB_PASSWORD} \
            my-odoo:${ODOO_IMAGE_TAG}

          for i in {1..60}; do
            if curl -fsS http://127.0.0.1:8069/web/login >/dev/null; then
              echo "✅ Odoo is reachable"
              break
            fi
            echo "Waiting Odoo..."
            sleep 2
          done

          curl -fsS http://127.0.0.1:8069/web/login | head -n 20

      - name: Cleanup
        if: always()
        run: |
          docker logs odoo-ci || true
          docker rm -f odoo-ci || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push to ECR
        run: |
          IMAGE="${{ secrets.ECR_REPO }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to ECS (force new deployment)
        run: |
          aws ecs update-service \
            --cluster "${{ secrets.ECS_CLUSTER }}" \
            --service "${{ secrets.ECS_SERVICE }}" \
            --force-new-deployment
